# 测试配置文件
# @author <a href="https://github.com/likason">kason</a>
# @from <a href="https://kason.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.8.32.2:3306/mianshiya
    username: mianshiya
    password: mianshiya
  # Redis 配置
  # todo 需替换配置 1
  redis:
    database: 1
    host: 119.8.32.2
    port: 6379
    timeout: 5000
#    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置1
  elasticsearch:
    uris: http://119.8.32.2:9200
    username: root
    password: 123456